version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  app:
    container_name: airbnb-similar
    restart: always
    build: .
    ports:
      - "80:1128"
    links:
      - mongo